### PR TITLE
Implement validation and tooltips, fixes marumari/decklist#5

### PR DESCRIPTION
**Pull request by Nightfirecat**
Creates a status box below the PDF / download button which displays warnings and errors regarding notes users should be mindful of when filling out the decklist sheet. Also implements tooltips on fields which are affected by any issues raised against them.

Updates jQuery UI to 1.11.2, includes the tooltip.js widget.
Closes marumari/decklist#5

### CODE REVIEW

**Comment by Nightfirecat** [comment]
P.S. These changes can be tested [on my gh-pages branch for this repository](http://nightfirecat.github.io/decklist/).

**Comment by marumari** [comment]
Wow, looking really really good.  I’m going to merge this and then make some tweaks before pushing it out to the website.  :)

**Comment by marumari** [comment]
Okay, I just made some updates.  Some minor CSS fixes, clarity on deck size.

I have noticed a bug that unrecognized cards no longer appear on the list.  That probably isn’t right.  :)

**Comment by marumari** [comment]
BTW, cloned my changes into here:
http://www.twoevils.org/html/mtg/beta/decklist/

**Comment by marumari** [comment]
Okay!  I think I fixed the issue with unrecognized cards disappearing.  If you could poke away at the below URL, and take a gander at today’s commits, I would really appreciate it.  :)

Thanks!

**Comment by marumari** [comment]
Thank gosh for it being a slow day at work.  I think I got all the changes I wanted put into the website, so I did a git pull on decklist.org.  You can see your fine work there.  Thanks so very much!  :D

**Comment by Nightfirecat** [comment]
All your modifications look just fine - loading the status before working on the PDF reload works really smoothly, and I definitely agree with hiding warning tooltips; the experience feels a lot less noisy that way.

> I have noticed a bug that unrecognized cards no longer appear on the list. That probably isn’t right. :)

That change was intentional, but I can understand the decision to leave them on the PDF.

**Comment by ChaimW** [comment]
Just as a suggestion, you might want to move that box to above the pdf view so that it isn't hidden (you need to scroll to see it)

**Comment by Nightfirecat** [comment]
You have to scroll down to enter the deck contents, so I'd imagine most people would notice it at that point. The PDF preview is, in my opinion, much more important.

**Pull request merged**
